/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-09 11:26:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/shop/../include/nav.jsp", Long.valueOf(1599648945358L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/footer.jsp", Long.valueOf(1599401013903L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/aside.jsp", Long.valueOf(1599462802271L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598605529490L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/header.jsp", Long.valueOf(1599394304246L));
    _jspx_dependants.put("jar:file:/C:/Users/GKY/project/pro0831/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Cherry/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/GKY/project/pro0831/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Cherry/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<title>Home</title>\n");
      out.write("\n");
      out.write("<!-- j.query -->\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- 부가적인 테마 -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\n");
      out.write("\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\t\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul {\n");
      out.write("\tpadding: 0;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tlist-style: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div#root {\n");
      out.write("\twidth: 90%;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header#header {\n");
      out.write("\tfont-size: 60px;\n");
      out.write("\tpadding: 20px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("header#header h1 a {\n");
      out.write("\tcolor: #000;\n");
      out.write("\tfont-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav#nav {\n");
      out.write("\tpadding: 10px;\n");
      out.write("\ttext-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("nav#nav ul li {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tmargin-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section#container {\n");
      out.write("\tpadding: 20px 0;\n");
      out.write("\tborder-top: 2px solid #eee;\n");
      out.write("\tborder-bottom: 2px solid #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("section#container::after {\n");
      out.write("\tcontent: \"\";\n");
      out.write("\tdisplay: block;\n");
      out.write("\tclear: both;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 200px;\n");
      out.write("}\n");
      out.write("/*  div#container_box { float:right; width:calc(100% - 200px - 20px); } */\n");
      out.write("aside#aside h3 {\n");
      out.write("\tfont-size: 22px;\n");
      out.write("\tmargin-bottom: 20px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside ul li {\n");
      out.write("\ttext-align: center;\n");
      out.write("\tmargin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside ul li a {\n");
      out.write("\tdisplay: block;\n");
      out.write("\twidth: 100%;\n");
      out.write("\tpadding: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside ul li a:hover {\n");
      out.write("\tbackground: #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li {\n");
      out.write("\tposition: relative;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li:hover {\n");
      out.write("\tbackground: #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li>ul.low {\n");
      out.write("\tdisplay: none;\n");
      out.write("\tposition: absolute;\n");
      out.write("\ttop: 0;\n");
      out.write("\tleft: 180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li:hover>ul.low {\n");
      out.write("\tdisplay: block;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li:hover>ul.low li a {\n");
      out.write("\tbackground: #eee;\n");
      out.write("\tborder: 1px solid #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li:hover>ul.low li a:hover {\n");
      out.write("\tbackground: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("aside#aside li>ul.low li {\n");
      out.write("\twidth: 180px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("\tcolor: #05f;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a:hover {\n");
      out.write("\ttext-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("footer#footer {\n");
      out.write("\tbackground: #f9f9f9;\n");
      out.write("\tpadding: 20px;\n");
      out.write("\tdisplay:;\n");
      out.write("\tmargin: 0 auto;\n");
      out.write("\tpadding-left: 20px;\n");
      out.write("\tfont-weight: 700;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("div.goods div.goodsImg {\n");
      out.write("\tfloat: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsImg img {\n");
      out.write("\twidth: 500px;\n");
      out.write("\theight: auto;\n");
      out.write("\tmargin-left: 20px\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo {\n");
      out.write("\tfloat: right;\n");
      out.write("\twidth: 400px;\n");
      out.write("\tfont-size: 22px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo p {\n");
      out.write("\tmargin: 2px 20px 20px 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo p span {\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\twidth: 100px;\n");
      out.write("\tmargin-right: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo p.cartStock input {\n");
      out.write("\tfont-size: 22px;\n");
      out.write("\twidth: 50px;\n");
      out.write("\tpadding: 5px;\n");
      out.write("\tmargin: 0;\n");
      out.write("\tborder: 1px solid #eee;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo p.cartStock button {\n");
      out.write("\tfont-size: 26px;\n");
      out.write("\tborder: none;\n");
      out.write("\tbackground: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.goodsInfo p.addToCart {\n");
      out.write("\ttext-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("div.goods div.gdsDes {\n");
      out.write("\tfont-size: 15px;\n");
      out.write("\tclear: both;\n");
      out.write("\tpadding-top: 30px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(" section.replyForm { padding:30px 0; }\n");
      out.write(" section.replyForm div.input_area { margin:10px 0; }\n");
      out.write(" section.replyForm textarea { font-size:16px; font-family:'맑은 고딕', verdana; padding:10px; width:98%; height:150px; pa }\n");
      out.write(" section.replyForm button { font-size:20px; padding:5px 10px; margin:10px 0; background:#fff; border:1px solid #ccc; }\n");
      out.write(" \n");
      out.write(" section.replyList { padding:30px 0; }\n");
      out.write(" section.replyList ol { padding:0; margin:0; }\n");
      out.write(" section.replyList ol li { padding:10px 0; border-bottom:2px solid #eee; }\n");
      out.write(" section.replyList div.userInfo { }\n");
      out.write(" section.replyList div.userInfo .userName { font-size:24px; font-weight:bold; }\n");
      out.write(" section.replyList div.userInfo .date { color:#999; display:inline-block; margin-left:10px; }\n");
      out.write(" section.replyList div.replyContent { padding:10px; margin:20px 0; }\n");
      out.write(" section.replyList div.replyFooter button { font-size:14px; border: 1px solid #999; background:none; margin-right:10px; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(" div.replyModal { position:relative; z-index:1; display: none;}\n");
      out.write(" div.modalBackground { position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0, 0, 0, 0.8); z-index:-1; }\n");
      out.write(" div.modalContent { position:fixed; top:20%; left:calc(50% - 250px); width:500px; height:250px; padding:20px 10px; background:#fff; border:2px solid #666; }\n");
      out.write(" div.modalContent textarea { font-size:16px; font-family:'맑은 고딕', verdana; padding:10px; width:480px; height:150px; }\n");
      out.write(" div.modalContent button { font-size:20px; padding:5px 10px; margin:10px 0; background:#fff; border:1px solid #ccc; }\n");
      out.write(" div.modalContent button.modal_cancel { margin-left:20px; }\n");
      out.write("</style>\t\n");
      out.write("\n");
      out.write("<script> \n");
      out.write("function replyList() {\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write(" var gdsNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write(" $.getJSON(\"/shop/view/replyList\" + \"?n=\" + gdsNum, function(data){\n");
      out.write("  var str = \"\";\n");
      out.write("  \n");
      out.write("  $(data).each(function(){\n");
      out.write("   \n");
      out.write("   console.log(data);\n");
      out.write("   \n");
      out.write("   var repDate = new Date(this.repDate);\n");
      out.write("   repDate = repDate.toLocaleDateString(\"ko-US\")\n");
      out.write("   \n");
      out.write("   //코드조립\n");
      out.write("   str += \"<li data-repNum='\" + this.repNum + \"'>\" //\"<li data-gdsNum='\" + this.gdsNum + \"'>\"\n");
      out.write("   + \"<div class='userInfo'>\"\n");
      out.write("   + \"<span class='userName'>\" + this.userName + \"</span>\"\n");
      out.write("   + \"<span class='date'>\" + repDate + \"</span>\"\n");
      out.write("   + \"</div>\"\n");
      out.write("   + \"<div class='replyContent'>\" + this.repCon + \"</div>\"\n");
      out.write("  \n");
      out.write("   + \"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("  \n");
      out.write("   + \"</li>\";          \n");
      out.write("  });\n");
      out.write("  \n");
      out.write("  $(\"section.replyList ol\").html(str);\n");
      out.write(" });\n");
      out.write(" }\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div id=\"root\">\n");
      out.write("\t\t<header id=\"header\">\n");
      out.write("\t\t\t<div id=\"header_box\">\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"title\">\r\n");
      out.write("\t<a href=\"/\">CherryFarm!</a>\r\n");
      out.write("\r\n");
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\n");
      out.write("\t\t<nav id=\"nav\">\n");
      out.write("\t\t\t<div id=\"nav_box\">\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</ul>");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\n");
      out.write("\t\t<section id=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"container_box\">\n");
      out.write("\t\t\t\t<section id=\"content\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<aside id=\"aside\">\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>상품목록</h3>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"/shop/list?c=100&l=1\">국산체리</a>\r\n");
      out.write("\t\t<ul class=\"low\">\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=101&l=2\">생체리</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/shop/list?c=102&l=2\">냉동</a></li>\r\n");
      out.write("\t\t</ul>\t\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li><a href=\"\">수입체리</a></li>\t\t\t\r\n");
      out.write("\t<li><a href=\"\">체리주스</a></li>\r\n");
      out.write("\t<li><a href=\"\">기타</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t\t\t\t</aside>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<form role=\"form\" method=\"post\">\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"gdsNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"goods\" style=\"padding-right: 50px\">\n");
      out.write("\t\t\t\t\t\t<div class=\"goodsImg\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"goodsInfo\">\n");
      out.write("\t\t\t\t\t\t\t<p class=\"gdsName\">\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: 'Noto Sans KR', sans-serif;\">상품명</span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class=\"cateName\">\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: 'Noto Sans KR', sans-serif;\">카테고리</span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.cateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class=\"gdsPrice\">\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: 'Noto Sans KR', sans-serif;\">가격\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t원\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class=\"gdsStock\">\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: 'Noto Sans KR', sans-serif;\">재고\n");
      out.write("\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\tEA\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class=\"cartStock\">\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-family: 'Noto Sans KR', sans-serif;\">구입\n");
      out.write("\t\t\t\t\t\t\t\t\t수량</span>\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"plus\">+</button>\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"number\" class=\"numBox\" min=\"1\"\n");
      out.write("\t\t\t\t\t\t\t\t\tmax=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"1\" readonly=\"readonly\" />\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"minus\">-</button>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<script>\n");
      out.write("  $(\".plus\").click(function(){\n");
      out.write("   var num = $(\".numBox\").val();\n");
      out.write("   var plusNum = Number(num) + 1;\n");
      out.write("   \n");
      out.write("   if(plusNum >= ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(") {\n");
      out.write("    $(\".numBox\").val(num);\n");
      out.write("//    } else {\n");
      out.write("    $(\".numBox\").val(plusNum);          \n");
      out.write("   }\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("  $(\".minus\").click(function(){\n");
      out.write("   var num = $(\".numBox\").val();\n");
      out.write("   var minusNum = Number(num) - 1;\n");
      out.write("   \n");
      out.write("   if(minusNum <= 0) {\n");
      out.write("    $(\".numBox\").val(num);\n");
      out.write("   } else {\n");
      out.write("    $(\".numBox\").val(minusNum);          \n");
      out.write("   }\n");
      out.write("  });\n");
      out.write(" </script>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<p class=\"addToCart\">\n");
      out.write(" <button type=\"button\" class=\"addCart_btn\">카트</button>\n");
      out.write(" \n");
      out.write("<script>\n");
      out.write(" $(\".addCart_btn\").click(function(){\n");
      out.write("  var gdsNum = $(\"#gdsNum\").val();\n");
      out.write("  var cartStock = $(\".numBox\").val();\n");
      out.write("           \n");
      out.write("  var data = {\n");
      out.write("    gdsNum : gdsNum,\n");
      out.write("    cartStock : cartStock\n");
      out.write("    };\n");
      out.write("  \n");
      out.write("  $.ajax({\n");
      out.write("   url : \"/shop/view/addCart\",\n");
      out.write("   type : \"post\",\n");
      out.write("   data : data,\n");
      out.write("   success : function(result){\n");
      out.write("    \n");
      out.write("    if(result == 1) {\n");
      out.write("     alert(\"카트 담기 성공\");\n");
      out.write("     $(\".numBox\").val(\"1\");\n");
      out.write("    } else {\n");
      out.write("     alert(\"회원만 사용할 수 있습니다.\")\n");
      out.write("     $(\".numBox\").val(\"1\");\n");
      out.write("    }\n");
      out.write("   },\n");
      out.write("   error : function(){\n");
      out.write("    alert(\"카트 담기 실패\");\n");
      out.write("   }\n");
      out.write("  });\n");
      out.write(" });\n");
      out.write("</script>\n");
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"gdsDes\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"text-align: right; font-family: 'Noto Sans KR', sans-serif;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsDes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div id=\"reply\">\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<section class=\"replyList\">\n");
      out.write("\t\t\t\t\t\t\t<ol>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<li> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t<div class=\"userInfo\"> -->\n");
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\t</div> -->\n");
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t</li> -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</ol>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("<script> \n");
      out.write("replyList();\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$(document).on(\"click\", \".modify\", function(){\n");
      out.write("\t //$(\".replyModal\").attr(\"style\", \"display:block;\");\n");
      out.write("\t $(\".replyModal\").fadeIn(200);\n");
      out.write("\t \n");
      out.write("\t var repNum = $(this).attr(\"data-repNum\");\n");
      out.write("\t var repCon = $(this).parent().parent().children(\".replyContent\").text();\n");
      out.write("\t \n");
      out.write("\t $(\".modal_repCon\").val(repCon);\n");
      out.write("\t $(\".modal_modify_btn\").attr(\"data-repNum\", repNum);\n");
      out.write("\t \n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write(" $(document).on(\"click\", \".delete\", function(){\n");
      out.write("\t \n");
      out.write("\t var deletConfirm = confirm(\"삭제 하시겠습니까?\");\n");
      out.write("\t \n");
      out.write("\t if(deletConfirm){\n");
      out.write("\t\t \n");
      out.write("  var data = {repNum : $(this).attr(\"data-repNum\")};\n");
      out.write("   \n");
      out.write("  $.ajax({\n");
      out.write("\t  url : \"/shop/view/deleteReply\",\n");
      out.write("\t  type : \"post\",\n");
      out.write("\t  data : data,\n");
      out.write("\t  success : function(result){\n");
      out.write("\t   \n");
      out.write("\t   if(result == 1) {\n");
      out.write("\t    replyList();\n");
      out.write("\t   } else {\n");
      out.write("\t    alert(\"작성자 본인만 할 수 있습니다.\");    \n");
      out.write("\t   }\n");
      out.write("\t  },\n");
      out.write("\t  error : function(){\n");
      out.write("\t   alert(\"로그인하셔야합니다.\")\n");
      out.write("\t  }\n");
      out.write("\t });\n");
      out.write(" }\n");
      out.write(" });\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</section>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</section>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<footer id=\"footer\">\n");
      out.write("\t\t<div id=\"footer_box\">\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer style=\"text-align: center\">Copyright(c) 2020 가영 All rights reserved.\r\n");
      out.write("\t<p style=\"text-align: center\">대전광역시 동구 우암로 368-21</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"replyModal\">\n");
      out.write("\n");
      out.write(" <div class=\"modalContent\">\n");
      out.write("  \n");
      out.write("  <div>\n");
      out.write("   <textarea class=\"modal_repCon\" name=\"modal_repCon\"></textarea>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  <div>\n");
      out.write("   <button type=\"button\" class=\"modal_modify_btn\">수정</button>\n");
      out.write("   <button type=\"button\" class=\"modal_cancel\">취소</button>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write(" </div>\n");
      out.write("\n");
      out.write("<div class=\"modalBackground\"></div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("$(\".modal_modify_btn\").click(function(){\n");
      out.write("\t var modifyConfirm = confirm(\"정말로 수정하시겠습니까?\");\n");
      out.write("\t \n");
      out.write("\t if(modifyConfirm) {\n");
      out.write("\t  var data = {\n");
      out.write("\t     repNum : $(this).attr(\"data-repNum\"),\n");
      out.write("\t     repCon : $(\".modal_repCon\").val()\n");
      out.write("\t    };  // ReplyVO 형태로 데이터 생성\n");
      out.write("\t  \n");
      out.write("\t  $.ajax({\n");
      out.write("\t   url : \"/shop/view/modifyReply\",\n");
      out.write("\t   type : \"post\",\n");
      out.write("\t   data : data,\n");
      out.write("\t   success : function(result){\n");
      out.write("\t    \n");
      out.write("\t    if(result == 1) {\n");
      out.write("\t     replyList();\n");
      out.write("\t     $(\".replyModal\").fadeOut(200);\n");
      out.write("\t    } else {\n");
      out.write("\t     alert(\"작성자 본인만 할 수 있습니다.\");       \n");
      out.write("\t    }\n");
      out.write("\t   },\n");
      out.write("\t   error : function(){\n");
      out.write("\t    alert(\"로그인하셔야합니다.\")\n");
      out.write("\t   }\n");
      out.write("\t  });\n");
      out.write("\t }\n");
      out.write("\t \n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\n");
      out.write("$(\".modal_cancel\").click(function(){\n");
      out.write("//  $(\".replyModal\").attr(\"style\", \"display:none;\");\n");
      out.write("$(\".replyModal\").fadeOut(200);\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/shop/view.jsp(255,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\"\n");
          out.write("  \n");
          out.write("   + \"<div class='replyFooter'>\"\n");
          out.write("   + \"<button type='button' class='modify' data-repNum='\" + this.repNum + \"'>수정</button>\"\n");
          out.write("   + \"<button type='button' class='delete' data-repNum='\" + this.repNum + \"'>삭제</button>\"\n");
          out.write("   + \"</div>\"\n");
          out.write("  \n");
          out.write("   + \"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/shop/../include/nav.jsp(15,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write(" <li>\r\n");
          out.write("  <a href=\"/member/signin\"><button type=\"button\" class=\"btn btn-warning\">로그인</button></a>\r\n");
          out.write(" </li>\r\n");
          out.write(" <li>\r\n");
          out.write("  <a href=\"/member/signup\"><button type=\"button\" class=\"btn btn-danger\">회원가입</button></a>\r\n");
          out.write(" </li>\r\n");
          out.write(" \r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/shop/../include/nav.jsp(24,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write(" <li>\r\n");
          out.write("  ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write(" </li>\r\n");
          out.write(" \r\n");
          out.write(" <li>\r\n");
          out.write(" \t<a href=\"/shop/cartList\">카트리스트</a>\r\n");
          out.write(" </li>\r\n");
          out.write(" \r\n");
          out.write(" <li>\r\n");
          out.write(" \t<a href=\"/shop/orderList\">주문 리스트</a>\r\n");
          out.write(" </li>\r\n");
          out.write(" \r\n");
          out.write(" <li>\r\n");
          out.write("  <a href=\"/member/signout\"><button type=\"button\" class=\"btn btn-danger\">로그아웃</button></a>\r\n");
          out.write(" </li>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/shop/../include/nav.jsp(26,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.verify == 9}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<li>\r\n");
          out.write(" <a href=\"/admin/index\">관리자 화면</a> \r\n");
          out.write("</li> \r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/shop/view.jsp(316,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("###,###,###");
      // /WEB-INF/views/shop/view.jsp(316,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsPrice}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/shop/view.jsp(323,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("###,###,###");
      // /WEB-INF/views/shop/view.jsp(323,8) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/shop/view.jsp(402,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t<p>\n");
          out.write("\t\t\t\t\t\t\t\t소감을 남기시려면 <a href=\"../member/signin\">로그인</a>해주세요\n");
          out.write("\t\t\t\t\t\t\t</p>\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/shop/view.jsp(408,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t<section class=\"replyForm\">\n");
          out.write("\t\t\t\t\t\t\t\t<form role=\"form\" method=\"post\" autocomplete=\"off\">\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"gdsNum\" id=\"gdsNum\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"input_area\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<textarea name=\"repCon\" id=\"repCon\"></textarea>\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"input_area\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"reply_btn\">상품후기</button>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\n");
          out.write("<script>\n");
          out.write(" $(\"#reply_btn\").click(function(){\n");
          out.write("  \n");
          out.write("  var formObj = $(\".replyForm form[role='form']\");\n");
          out.write("  var gdsNum = $(\"#gdsNum\").val();\n");
          out.write("  var repCon = $(\"#repCon\").val()\n");
          out.write("  \n");
          out.write("  var data = {\n");
          out.write("    gdsNum : gdsNum,\n");
          out.write("    repCon : repCon\n");
          out.write("    };\n");
          out.write("  \n");
          out.write("  $.ajax({\n");
          out.write("   url : \"/shop/view/registReply\",\n");
          out.write("   type : \"post\",\n");
          out.write("   data : data,\n");
          out.write("   success : function(){\n");
          out.write("    replyList();\n");
          out.write("    $(\"#repCon\").val(\"\");\n");
          out.write("   }\n");
          out.write("  });\n");
          out.write(" });\n");
          out.write("</script>\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t</form>\n");
          out.write("\t\t\t\t\t\t\t</section>\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }
}
