/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-06 15:19:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/views/admin/goods/../include/aside.jsp", Long.valueOf(1599405186618L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598605529490L));
    _jspx_dependants.put("/WEB-INF/views/admin/goods/../include/footer.jsp", Long.valueOf(1599405234359L));
    _jspx_dependants.put("jar:file:/C:/Users/GKY/project/pro0831/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Cherry/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/admin/goods/../include/nav.jsp", Long.valueOf(1599109262027L));
    _jspx_dependants.put("/WEB-INF/views/admin/goods/../include/header.jsp", Long.valueOf(1599405342491L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- j.query -->\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/resources/ckeditor/ckeditor.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: '맑은 고딕', verdana;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#root {\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header#header {\r\n");
      out.write("\tfont-size: 60px;\r\n");
      out.write("\tpadding: 20px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header#header h1 a {\r\n");
      out.write("\tcolor: #000;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav#nav {\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav#nav ul li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section#container {\r\n");
      out.write("\tpadding: 20px 0;\r\n");
      out.write("\tborder-top: 2px solid #eee;\r\n");
      out.write("\tborder-bottom: 2px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section#container::after {\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tclear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#container_box {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\twidth: calc(100% - 200px - 20px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside ul li {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside ul li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("aside ul li a:hover {\r\n");
      out.write("\tbackground: #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer#footer {\r\n");
      out.write("\tbackground: #f9f9f9;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer#footer ul li {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".inputArea {\r\n");
      out.write("\tmargin: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label[for='gdsDes'] {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea#gdsDes {\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select_img img {\r\n");
      out.write("\tmargin:30px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"root\">\r\n");
      out.write("\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t<div id=\"header_box\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<style>\r\n");
      out.write(" body { font-family:'맑은 고딕', verdana; padding:0; margin:0; }\r\n");
      out.write(" ul { padding:0; margin:0; list-style:none;  }\r\n");
      out.write("\r\n");
      out.write(" div#root { width:90%; margin:0 auto; }\r\n");
      out.write(" \r\n");
      out.write(" header#header { font-size:60px; padding:20px 0; }\r\n");
      out.write(" header#header h1 a { color:#000; font-weight:bold; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Admin</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"title\">\r\n");
      out.write("\t<a href=\"/\">CherryFarm!</a>\r\n");
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\r\n");
      out.write("\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t<div id=\"nav_box\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t\t<section id=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<aside>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<aside>\r\n");
      out.write(" <ul>\r\n");
      out.write("  <li><a href=\"/admin/goods/list\">상품목록</a></li>\r\n");
      out.write("  <li><a href=\"/admin/goods/register\">상품등록</a></li>\r\n");
      out.write("  <li><a href=\"\">상품소감</a></li>\r\n");
      out.write("  <li><a href=\"\">유저목록</a></li>\r\n");
      out.write(" </ul>\r\n");
      out.write("</aside>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"container_box\">\r\n");
      out.write("\t\t\t\t<h2>상품 등록</h2>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form role=\"form\" method=\"post\" autocomplete=\"off\" enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label>1차 분류</label> <select class=\"category1\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t</select> <label>2차 분류</label> <select class=\"category2\" name=\"cateCode\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gdsName\">상품명</label> <input type=\"text\" id=\"gdsName\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"gdsName\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gdsPrice\">상품가격</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"gdsPrice\" name=\"gdsPrice\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gdsStock\">상품수량</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"gdsStock\" name=\"gdsStock\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gdsDes\">상품소개</label>\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"5\" cols=\"50\" id=\"gdsDes\" name=\"gdsDes\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write(" var ckeditor_config = {\r\n");
      out.write("   resize_enaleb : false,\r\n");
      out.write("   enterMode : CKEDITOR.ENTER_BR,\r\n");
      out.write("   shiftEnterMode : CKEDITOR.ENTER_P,\r\n");
      out.write("   filebrowserUploadUrl : \"/admin/goods/ckUpload\"\r\n");
      out.write(" };\r\n");
      out.write(" \r\n");
      out.write(" CKEDITOR.replace(\"gdsDes\", ckeditor_config);\r\n");
      out.write("</script>\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<label for=\"gdsImg\">이미지</label> <input type=\"file\" id=\"gdsImg\"\r\n");
      out.write("\t\t\t\t\t\t\tname=\"file\" />\r\n");
      out.write("\t\t\t\t\t\t<div class=\"select_img\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#gdsImg\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.change(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tif (this.files && this.files[0]) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvar reader = new FileReader;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treader.onload = function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\".select_img img\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.attr(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"src\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata.target.result)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.width(500);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\treader\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.readAsDataURL(this.files[0]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(request.getRealPath("/") );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"inputArea\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"register_Btn\" class=\"btn btn-primary\">등록</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t\t<footer id=\"footer\">\r\n");
      out.write("\t\t\t<div id=\"footer_box\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer style=\"text-align: center\">Copyright(c) 2020 가영 All rights reserved.\r\n");
      out.write("\t<p style=\"text-align: center\">대전광역시 동구 우암로 368-21</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 컨트롤러에서 데이터 받기\r\n");
      out.write("\t\tvar jsonData = JSON.parse('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\r\n");
      out.write("\t\tconsole.log(jsonData);\r\n");
      out.write("\r\n");
      out.write("\t\tvar cate1Arr = new Array();\r\n");
      out.write("\t\tvar cate1Obj = new Object();\r\n");
      out.write("\r\n");
      out.write("\t\t// 1차 분류 셀렉트 박스에 삽입할 데이터 준비\r\n");
      out.write("\t\tfor (var i = 0; i < jsonData.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (jsonData[i].level == \"1\") {\r\n");
      out.write("\t\t\t\tcate1Obj = new Object(); //초기화\r\n");
      out.write("\t\t\t\tcate1Obj.cateCode = jsonData[i].cateCode;\r\n");
      out.write("\t\t\t\tcate1Obj.cateName = jsonData[i].cateName;\r\n");
      out.write("\t\t\t\tcate1Arr.push(cate1Obj);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// 1차 분류 셀렉트 박스에 데이터 삽입\r\n");
      out.write("\t\tvar cate1Select = $(\"select.category1\")\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = 0; i < cate1Arr.length; i++) {\r\n");
      out.write("\t\t\tcate1Select.append(\"<option value='\" + cate1Arr[i].cateCode + \"'>\"\r\n");
      out.write("\t\t\t\t\t+ cate1Arr[i].cateName + \"</option>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//2차\r\n");
      out.write("\t\t$(document)\r\n");
      out.write("\t\t\t\t.on(\r\n");
      out.write("\t\t\t\t\t\t\"change\",\r\n");
      out.write("\t\t\t\t\t\t\"select.category1\",\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar cate2Arr = new Array();\r\n");
      out.write("\t\t\t\t\t\t\tvar cate2Obj = new Object();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 2차 분류 셀렉트 박스에 삽입할 데이터 준비\r\n");
      out.write("\t\t\t\t\t\t\tfor (var i = 0; i < jsonData.length; i++) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tif (jsonData[i].level == \"2\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcate2Obj = new Object(); //초기화\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcate2Obj.cateCode = jsonData[i].cateCode;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcate2Obj.cateName = jsonData[i].cateName;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcate2Obj.cateCodeRef = jsonData[i].cateCodeRef;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcate2Arr.push(cate2Obj);\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar cate2Select = $(\"select.category2\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t\t\tfor(var i = 0; i < cate2Arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t  cate2Select.append(\"<option value='\" + cate2Arr[i].cateCode + \"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t       + cate2Arr[i].cateName + \"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t */\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tcate2Select.children().remove();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$(\"option:selected\", this)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.each(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar selectVal = $(this).val();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tcate2Select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\"<option value='\"+selectVal+\"'>전체</option>\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tfor (var i = 0; i < cate2Arr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tif (selectVal == cate2Arr[i].cateCodeRef) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tcate2Select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.append(\"<option value='\" + cate2Arr[i].cateCode + \"'>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ cate2Arr[i].cateName\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"</option>\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var regExp = /[^0-9]/gi;\r\n");
      out.write("\r\n");
      out.write("$(\"#gdsPrice\").keyup(function(){ numCheck($(this)); });\r\n");
      out.write("$(\"#gdsStock\").keyup(function(){ numCheck($(this)); });\r\n");
      out.write("\r\n");
      out.write("function numCheck(selector) {\r\n");
      out.write(" var tempVal = selector.val();\r\n");
      out.write(" selector.val(tempVal.replace(regExp, \"\"));\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/admin/goods/../include/nav.jsp(5,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("<li>\r\n");
          out.write(" <a href=\"/\">일반 화면</a> \r\n");
          out.write("</li> \r\n");
          out.write("\r\n");
          out.write(" <li>\r\n");
          out.write("  <a href=\"/member/signout\">로그아웃</a>\r\n");
          out.write(" </li>\r\n");
          out.write("\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
